configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/graphor%2Fgraphor-typescript-project-733639cf67aeccafb834ff2b4f7ad14b433a7ef23361a304884bc0c0ec081036.yml
openapi_spec_hash: 1b4b0d16f4cae0ca70dafb3f50d93bf0
config_hash: e200507d25b81f5ded1f621a764bad9d
